#!/bin/bash

# =============================================================================
# IBM Cloud Toolkit for watsonx Orchestrate on IBM Cloud — Installer
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

print_header() {
    echo ""
    echo -e "${BOLD}${BLUE}============================================================${NC}"
    echo -e "${BOLD}${BLUE}  $1${NC}"
    echo -e "${BOLD}${BLUE}============================================================${NC}"
    echo ""
}

print_step()    { echo -e "${CYAN}▶  $1${NC}"; }
print_success() { echo -e "${GREEN}✅  $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️   $1${NC}"; }
print_error()   { echo -e "${RED}❌  $1${NC}"; }
ask_user()      { echo -e "${YELLOW}❓  $1${NC}"; }

clear
echo -e "${BOLD}${BLUE}"
cat << 'EOF'
  _____ ____  __  __    ____ _                 _   _____           _ _    _ _
 |_   _|  _ \|  \/  |  / ___| | ___  _   _  __| | |_   _|__   ___| | | _(_) |_
   | | | |_) | |\/| | | |   | |/ _ \| | | |/ _` |   | |/ _ \ / _ \ | |/ / | __|
   | | |  _ <| |  | | | |___| | (_) | |_| | (_| |   | | (_) |  __/ |   <| | |_
   |_| |_| \_\_|  |_|  \____|_|\___/ \__,_|\__,_|   |_|\___/ \___|_|_|\_\_|\__|

         for watsonx Orchestrate on IBM Cloud — Installer
EOF
echo -e "${NC}"
echo -e "${BOLD}  Services: Code Engine | Cloud Logs | Cloud Monitoring | IBM Cloud Databases${NC}"
echo ""

# ─── Step 1: Prerequisites ────────────────────────────────────────────────────
print_header "STEP 1 of 6 — Checking Prerequisites"

check_command() {
    if command -v "$1" &> /dev/null; then
        print_success "$1 is installed"
        return 0
    else
        print_error "$1 is NOT installed"
        return 1
    fi
}

MISSING=0
check_command python3 || MISSING=1
check_command pip3    || MISSING=1
check_command curl    || MISSING=1
check_command git     || MISSING=1

if [ $MISSING -eq 1 ]; then
    echo ""
    print_error "Some required tools are missing. Please install them and re-run."
    echo "  On macOS:   brew install python3 git curl"
    echo "  On Ubuntu:  sudo apt-get install python3 python3-pip git curl"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | awk '{print $2}')
print_success "Python version: $PYTHON_VERSION"

# ─── Step 2: IBM Cloud + Orchestrate credentials ──────────────────────────────
print_header "STEP 2 of 6 — IBM Cloud & watsonx Orchestrate Configuration"

echo -e "${BOLD}We need your IBM Cloud credentials and watsonx Orchestrate instance details.${NC}"
echo -e "These are stored only in a local .env file on your machine."
echo ""

if [ -f ".env" ]; then
    print_warning ".env file already exists. Overwrite it? (y/n)"
    read -r OVERWRITE
    if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
        print_step "Keeping existing .env file..."
        source .env
    else
        rm .env
    fi
fi

if [ ! -f ".env" ]; then
    # IBM Cloud API Key
    echo -e "${YELLOW}Where to find your IBM Cloud API Key:${NC}"
    echo "  IBM Cloud Console → Manage → Access (IAM) → API Keys → Create"
    echo ""
    ask_user "Enter your IBM Cloud API Key:"
    read -rs IBM_CLOUD_API_KEY
    echo ""

    # Region
    echo ""
    echo -e "${YELLOW}Available regions: us-south, eu-de, eu-gb, jp-tok, au-syd${NC}"
    ask_user "Enter your IBM Cloud Region [default: us-south]:"
    read -r IBM_CLOUD_REGION
    IBM_CLOUD_REGION=${IBM_CLOUD_REGION:-us-south}

    # Resource Group
    echo ""
    ask_user "Enter your Resource Group name [default: Default]:"
    read -r IBM_RESOURCE_GROUP
    IBM_RESOURCE_GROUP=${IBM_RESOURCE_GROUP:-Default}

    # watsonx Orchestrate Instance URL
    echo ""
    echo -e "${YELLOW}watsonx Orchestrate Instance URL:${NC}"
    echo "  Find it: IBM Cloud Console → Resource list → AI/ML →"
    echo "           watsonx Orchestrate → your instance → Manage → Credentials"
    echo "  Example: https://my-instance.orchestrate.cloud.ibm.com"
    echo ""
    ask_user "Enter your watsonx Orchestrate Instance URL (or press Enter to skip):"
    read -r WATSONX_ORCHESTRATE_INSTANCE_URL

    cat > .env << ENVEOF
# IBM Cloud Toolkit for watsonx Orchestrate on IBM Cloud
# Generated by install.sh on $(date)

# IBM Cloud Credentials
IBM_CLOUD_API_KEY=${IBM_CLOUD_API_KEY}
IBM_CLOUD_REGION=${IBM_CLOUD_REGION}
IBM_CLOUD_RESOURCE_GROUP=${IBM_RESOURCE_GROUP}

# IBM Cloud API Endpoints
IBM_IAM_TOKEN_URL=https://iam.cloud.ibm.com/identity/token
IBM_CODE_ENGINE_API=https://api.${IBM_CLOUD_REGION}.codeengine.cloud.ibm.com/v2
IBM_CLOUD_LOGS_API=https://logs.private.${IBM_CLOUD_REGION}.logging.cloud.ibm.com/v1
IBM_MONITORING_API=https://${IBM_CLOUD_REGION}.monitoring.cloud.ibm.com
IBM_DATABASES_API=https://api.${IBM_CLOUD_REGION}.databases.cloud.ibm.com/v5/ibm

# watsonx Orchestrate on IBM Cloud
WATSONX_ORCHESTRATE_INSTANCE_URL=${WATSONX_ORCHESTRATE_INSTANCE_URL}
WATSONX_ORCHESTRATE_REGION=${IBM_CLOUD_REGION}

# Toolkit Settings
ADK_TOOLKIT_NAME=ibm-cloud-toolkit
ADK_TOOLKIT_VERSION=1.0.0
ENVEOF

    print_success ".env file created!"
fi

source .env

# ─── Step 3: Python virtual environment ───────────────────────────────────────
print_header "STEP 3 of 6 — Setting Up Python Environment"

print_step "Creating Python virtual environment..."
python3 -m venv venv
print_success "Virtual environment created at ./venv"

print_step "Activating virtual environment..."
source venv/bin/activate
print_success "Virtual environment activated"

print_step "Upgrading pip..."
pip install --upgrade pip --quiet
print_success "pip upgraded"

# ─── Step 4: Install dependencies ─────────────────────────────────────────────
print_header "STEP 4 of 6 — Installing Python Dependencies"

print_step "Installing required packages..."
pip install \
    ibm-cloud-sdk-core \
    ibm-platform-services \
    requests \
    python-dotenv \
    pydantic \
    httpx \
    rich \
    typer \
    --quiet

print_success "All Python dependencies installed!"

# ─── Step 5: Test IBM Cloud connection ────────────────────────────────────────
print_header "STEP 5 of 6 — Verifying IBM Cloud Connection"

print_step "Testing IBM Cloud authentication..."
python3 tools/test_connection.py
if [ $? -eq 0 ]; then
    print_success "IBM Cloud connection verified!"
else
    print_warning "Could not verify IBM Cloud connection. Check your API key."
    print_warning "You can still continue — auth will be retried at runtime."
fi

# ─── Step 6: Register tools ───────────────────────────────────────────────────
print_header "STEP 6 of 6 — Generating OpenAPI Spec for watsonx Orchestrate"

print_step "Registering all IBM Cloud tools and generating spec..."
python3 tools/register_tools.py

print_success "OpenAPI spec generated at config/ibm_cloud_toolkit_openapi.json"

# ─── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}============================================================${NC}"
echo -e "${BOLD}${GREEN}  🎉  Installation Complete!${NC}"
echo -e "${BOLD}${GREEN}============================================================${NC}"
echo ""
echo -e "${BOLD}IBM Cloud Tools Ready:${NC}"
echo ""
echo -e "  ${CYAN}📦 Code Engine${NC}      → List, create, delete apps & jobs"
echo -e "  ${CYAN}📋 Cloud Logs${NC}       → Search, tail, and analyze logs"
echo -e "  ${CYAN}📊 Monitoring${NC}       → Query metrics, manage alerts"
echo -e "  ${CYAN}🗄️  Databases${NC}        → Manage ICD instances & backups"
echo ""
echo -e "${BOLD}Next Steps — Import into watsonx Orchestrate on IBM Cloud:${NC}"
echo ""
echo -e "  1. Run the import guide:"
echo -e "     ${YELLOW}python3 tools/export_to_orchestrate.py${NC}"
echo ""
echo -e "  2. Or manually upload this file in the IBM Cloud Console:"
echo -e "     ${YELLOW}config/ibm_cloud_toolkit_openapi.json${NC}"
echo -e "     (IBM Cloud → watsonx Orchestrate → Skills & Apps → + Add skills)"
echo ""
echo -e "  3. Test a tool directly:"
echo -e "     ${YELLOW}source venv/bin/activate && python3 tools/code_engine_tools.py${NC}"
echo ""
echo -e "  4. Read the full guide:"
echo -e "     ${YELLOW}cat docs/GUIDE.md${NC}"
echo ""
