"""
export_to_orchestrate.py — Export Tools to watsonx Orchestrate on IBM Cloud
=============================================================================
This script helps you import the IBM Cloud toolkit into
watsonx Orchestrate on IBM Cloud using the OpenAPI spec
generated by register_tools.py.

Usage:
  python3 tools/export_to_orchestrate.py

The script will:
  1. Validate the OpenAPI spec exists
  2. Show your IBM Cloud Orchestrate instance details
  3. Give step-by-step instructions for importing into Orchestrate on IBM Cloud
"""

import os
import sys
import json
from pathlib import Path


def main():
    config_dir = Path(__file__).parent.parent / "config"
    spec_path = config_dir / "ibm_cloud_toolkit_openapi.json"
    manifest_path = config_dir / "tool_manifest.json"

    orchestrate_instance = os.getenv("WATSONX_ORCHESTRATE_INSTANCE_URL", "")
    orchestrate_api_key = os.getenv("IBM_CLOUD_API_KEY", "")
    region = os.getenv("IBM_CLOUD_REGION", "us-south")

    print()
    print("=" * 65)
    print("  IBM Cloud Toolkit → watsonx Orchestrate on IBM Cloud")
    print("=" * 65)
    print()

    if not spec_path.exists():
        print("❌ OpenAPI spec not found. Run this first:")
        print("   python3 tools/register_tools.py")
        sys.exit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    print(f"✅ Toolkit: {manifest['toolkit_name']} v{manifest['toolkit_version']}")
    print(f"   Tools available: {manifest['tool_count']}")
    print()

    if orchestrate_instance:
        print(f"✅ Orchestrate Instance URL: {orchestrate_instance}")
    else:
        print("⚠️  WATSONX_ORCHESTRATE_INSTANCE_URL not set in .env")
        print("   Add it to use the API import method below.")
    print()

    # ─── METHOD 1: IBM Cloud Console UI ───────────────────────────────────
    print("─" * 65)
    print("  METHOD 1 — Import via IBM Cloud Console UI (Recommended)")
    print("─" * 65)
    print()
    print("  1. Log in to IBM Cloud:")
    print("     → https://cloud.ibm.com")
    print()
    print("  2. From the Navigation menu, go to:")
    print("     'AI / Machine Learning' → 'watsonx Orchestrate'")
    print()
    print("  3. Open your watsonx Orchestrate instance.")
    print()
    print("  4. In the left sidebar, click 'Skills & Apps'")
    print()
    print("  5. Click '+ Add skills' → 'From OpenAPI file'")
    print()
    print(f"  6. Upload this file:")
    print(f"     📄 {spec_path.absolute()}")
    print()
    print(f"  7. Review the {manifest['tool_count']} tools listed → click 'Add'")
    print()
    print("  8. Go to 'Agent Builder' → open or create your agent →")
    print("     add the 'IBM Cloud Toolkit' skill set to your agent.")
    print()

    # ─── METHOD 2: watsonx Orchestrate REST API ────────────────────────────
    print("─" * 65)
    print("  METHOD 2 — Import via watsonx Orchestrate API")
    print("─" * 65)
    print()
    print("  Prerequisites:")
    print("   • WATSONX_ORCHESTRATE_INSTANCE_URL set in your .env")
    print("   • IBM Cloud IAM API key (IBM_CLOUD_API_KEY)")
    print()
    print("  Step 1 — Get an IAM token:")
    print()
    print('   curl -X POST "https://iam.cloud.ibm.com/identity/token" \\')
    print('     -H "Content-Type: application/x-www-form-urlencoded" \\')
    print('     -d "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=YOUR_API_KEY"')
    print()
    print("  Step 2 — Import the OpenAPI spec:")
    print()
    instance_url = orchestrate_instance or "https://YOUR_INSTANCE.orchestrate.cloud.ibm.com"
    print(f'   curl -X POST "{instance_url}/api/v1/skills/import" \\')
    print('     -H "Authorization: Bearer YOUR_IAM_TOKEN" \\')
    print('     -H "Content-Type: application/json" \\')
    print(f'     -d @{spec_path.absolute()}')
    print()

    # ─── METHOD 3: IBM Cloud CLI + watsonx plugin ──────────────────────────
    print("─" * 65)
    print("  METHOD 3 — Import via IBM Cloud CLI")
    print("─" * 65)
    print()
    print("  Step 1 — Install the IBM Cloud CLI (if not already):")
    print("   curl -fsSL https://clis.cloud.ibm.com/install/osx | sh")
    print()
    print("  Step 2 — Log in:")
    print("   ibmcloud login --apikey YOUR_API_KEY -r", region)
    print()
    print("  Step 3 — Target your watsonx Orchestrate instance:")
    print("   ibmcloud resource service-instances --service-name watsonx-orchestrate")
    print()
    print("  Step 4 — Import skills via the Orchestrate CLI plugin:")
    print("   ibmcloud wx-orchestrate skills import \\")
    print(f"     --spec {spec_path.absolute()}")
    print()

    # ─── Configure .env for Orchestrate ───────────────────────────────────
    print("─" * 65)
    print("  CONFIGURE YOUR .ENV FILE FOR ORCHESTRATE")
    print("─" * 65)
    print()
    print("  Add these variables to your .env file:")
    print()
    print("   # watsonx Orchestrate on IBM Cloud")
    print("   WATSONX_ORCHESTRATE_INSTANCE_URL=https://YOUR_INSTANCE.orchestrate.cloud.ibm.com")
    print("   WATSONX_ORCHESTRATE_REGION=us-south   # or eu-de, jp-tok, etc.")
    print()
    print("  Find your instance URL:")
    print("   IBM Cloud Console → Resource list → AI/ML →")
    print("   watsonx Orchestrate → your instance → Manage → Credentials")
    print()

    # ─── Verify after import ───────────────────────────────────────────────
    print("─" * 65)
    print("  VERIFY — Test prompts after importing")
    print("─" * 65)
    print()
    print("  In watsonx Orchestrate chat, try these prompts:")
    print()
    print('  💬 "List all my Code Engine projects"')
    print('  💬 "Show me errors from the last hour in my logs"')
    print('  💬 "What is my database CPU usage over the past 30 minutes?"')
    print('  💬 "List my IBM Cloud Database instances"')
    print()

    print("─" * 65)
    print("  FILES GENERATED")
    print("─" * 65)
    print()
    print(f"  📄 OpenAPI Spec   → {spec_path}")
    print(f"  📄 Tool Manifest  → {manifest_path}")
    print(f"  📄 Tool Summary   → {config_dir / 'tools_summary.txt'}")
    print()
    print("✅ Ready to import into watsonx Orchestrate on IBM Cloud!")
    print()


if __name__ == "__main__":
    main()
